version: '3'

services:
  chromeB:
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME --port 5555" /opt/bin/entry_point.sh'
    image: selenium/node-chrome:91.0@sha256:e93ae4127e3202aa79dd8a2d96eecbc8460ecce1bff2ed70f8f2d1aa1679beaa
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=localhost
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1
    network_mode: "host"
    volumes:
      - /dev/shm:/dev/shm

  firefox:
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME --port 5558" /opt/bin/entry_point.sh'
    image: selenium/node-firefox:89.0.1@sha256:42da03f9fdea62f8d6fcfe9691d977b1fdfdb81d3cb94b7f6d2d6694988afe62
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=localhost
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1
    network_mode: "host"
    volumes:
      - /dev/shm:/dev/shm

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.0.0@sha256:cd56f2d35c9643094887e6c57af99580fc5f3fe9e59037f35be9c78c7f068acb
    network_mode: "host"
