name: CI

on: [create, pull_request, push]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - name: Docker Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0 # renovate: tag=v1.5.1

      - name: Registry login
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER_NAME }}" --password-stdin

      - name: Build
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build \
            --build-arg CI="$CI" \
            --build-arg HOST_IP=172.17.0.1 \
            --cache-from=$IMAGE_ID:cache \
            --load \
            --network=host \
            -t stage_build \
            --target build \
            .
          docker container create --name extract stage_build
          docker container cp extract:/srv/app/ ./dist/
          docker container rm -f extract

          # Push the Docker image to the registry on git pushes that either pushed a tag or one of the following branches: [master, develop]
          if [[
            (
              "${{ github.event_name }}" == "create"
              &&
              ${{ startsWith(github.ref, 'refs/tags/') }} == "true"
            )
            ||
            (
              "${{ github.event_name }}" == "push"
              &&
              ${{ startsWith(github.ref, 'refs/heads/') }} == "true"
              &&
              (
                $VERSION == "latest"
                ||
                $VERSION == "develop"
              )
            )
          ]]
          then
            docker buildx build \
              --build-arg CI="$CI" \
              --build-arg HOST_IP=172.17.0.1 \
              --cache-from=$IMAGE_ID:cache \
              --cache-to=$IMAGE_ID:cache \
              --network=host \
              --push \
              -t $IMAGE_ID:$VERSION \
              .
          else
            docker buildx build \
              --build-arg CI="$CI" \
              --build-arg HOST_IP=172.17.0.1 \
              --cache-from=$IMAGE_ID:cache \
              --network=host \
              -t $IMAGE_ID:$VERSION \
              .
          fi

      - name: Zip
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28 # renovate: tag=v1.0.0
        with:
          args: zip -qq -r ./maevsi.zip ./dist/

      - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        with:
          name: maevsi.zip
          path: ./maevsi.zip
          retention-days: 1
  semantic-release:
    if: github.event_name != 'pull_request'
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@116647291d9b7bef1f5a4315deedd3f46ed4218b # renovate: tag=v2.5.4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-assets:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release Assets
    runs-on: ubuntu-latest
    needs: semantic-release
    steps:
      - uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
        with:
          name: maevsi.zip

      - name: GitHub Release Asset
        uses: softprops/action-gh-release@487fcd94425dd56e168af76ef300c3b4bd2a46fa # renovate: tag=v1
        with:
          files: maevsi.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
