name: Docker

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  prepare:
    name: 'Prepare'
    uses: dargmuesli/github-actions/.github/workflows/docker2.yml@0.16.5
    with:
      TARGET: prepare
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  lint:
    needs: prepare
    name: 'Lint'
    uses: dargmuesli/github-actions/.github/workflows/docker2.yml@0.16.5
    with:
      TARGET: lint
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  test-code:
    needs: prepare
    name: 'Test: code'
    uses: dargmuesli/github-actions/.github/workflows/docker2.yml@0.16.5
    with:
      TARGET: test
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  test-visual:
    needs: prepare
    name: 'Test: visual'
    uses: dargmuesli/github-actions/.github/workflows/docker2.yml@0.16.5
    with:
      TARGET: test-visual
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  build:
    needs: [lint, test-code, test-visual]
    name: 'Build'
    uses: dargmuesli/github-actions/.github/workflows/docker2.yml@0.16.5
    with:
      TARGET: production
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.16.5
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  release-assets:
    needs: release-semantic
    name: Release Assets
    uses: dargmuesli/github-actions/.github/workflows/release-assets.yml@0.16.5
