name: Docker

on: [pull_request, push]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER_NAME }}" --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: Build
        run: |
          docker build -t stage_build --target build .
          docker container create --name extract stage_build
          docker container cp extract:/srv/app/dist/ .
          docker container rm -f extract

      - name: Variables
        run: |
          IMAGE_ID=${{ github.repository }}
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

      - name: Run Buildx w/ push
        if: github.event_name == 'push'
        run: |
          docker buildx build \
            --cache-from=$IMAGE_ID:cache \
            --cache-to=$IMAGE_ID:cache \
            --push \
            -t $IMAGE_ID:$VERSION .

      - name: Run Buildx w/o push
        if: github.event_name == 'pull_request'
        run: |
          docker buildx build \
            --cache-from=$IMAGE_ID:cache \
            -t $IMAGE_ID:$VERSION .
        
      - name: Zip
        uses: montudor/action-zip@v0.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: zip -qq -r ./maevsi.zip ./dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: maevsi.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
